//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonAdminApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokemon
    {
        public int Id { get; set; }
        public string Navn { get; set; }
        public string Beskrivelse { get; set; }
        public string BildeSrc { get; set; }
        public Nullable<int> TrenerId { get; set; }
    
        public virtual Trener Trener { get; set; }
    }
}
